apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: default
  labels:
    app: bb
  name: gooddeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bb
  template:
    metadata:
      labels:
        app: bb
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: busybox
          image: busybox
          command: [ "sh", "-c", "sleep 1h" ]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: 96Mi
              cpu: 1
